# Generated by Django 4.2.16 on 2024-09-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='folowing',
            new_name='following',
        ),
    ]
